routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::post('bookings', 'BookingController@store')->name('bookings.store');
Route::get('bookings/{uid}', 'BookingController@show')->name('bookings.show');
Route::get('bookings/{uid}/edit', 'BookingController@edit')->name('bookings.edit');
Route::delete('bookings/{uid}', 'BookingController@destroy')->name('bookings.destroy');
Route::post('bookings/{uid}/update', 'BookingController@update')->name('bookings.update');
Route::post('bookings/{uid}/stop', 'BookingController@stop')->name('bookings.stop');
Route::post('bookings/{uid}/resume', 'BookingController@resume')->name('bookings.resume');
Route::get('bookings/{uid}/pay', 'BookingController@getPay')->name('bookings.pay');
Route::post('bookings/{uid}/pay', 'BookingController@postPay')->name('bookings.pay.post');

Route::get('contact', 'ContactController@form')->name('contact');
Route::post('contact', 'ContactController@send')->name('contact.post');
Route::get('contact/thanks', 'ContactController@thanks')->name('contact.thanks');

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::redirect('/', '/admin/bookings');

    Route::patch('bookings/{booking}/start', 'BookingController@start')->name('bookings.start');
    Route::patch('bookings/{booking}/restore', 'BookingController@restore')->name('bookings.restore');
    Route::get('bookings/{booking}/emails/notification/resend', 'BookingController@resendNotificationEmail')->name('bookings.emails.notification.resend');
    Route::resource('bookings', 'BookingController')->except(['create', 'show']);

    Route::get('black-outs', 'BlackOutController@index')->name('black-outs.index');
    Route::get('black-outs/create', 'BlackOutController@create')->name('black-outs.create');
    Route::post('black-outs', 'BlackOutController@store')->name('black-outs.store');
    Route::get('black-outs/{blackOut}/edit', 'BlackOutController@edit')->name('black-outs.edit');
    Route::patch('black-outs/{blackOut}', 'BlackOutController@update')->name('black-outs.update');
    Route::delete('black-outs/{blackOut}', 'BlackOutController@destroy')->name('black-outs.destroy');

    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/create', 'UserController@create')->name('users.create');
    Route::post('users', 'UserController@store')->name('users.store');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::patch('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
});

app/Models/Booking.php
<?php

namespace App\Models;

use App\Events\BookingCreating;
use App\Events\BookingDeleted;
use App\Events\BookingUpdated;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Stripe\Charge;
use Stripe\Stripe;

class Booking extends Model
{
    use SoftDeletes;

    /**
     * Ther attributes that should always be mutated and appended to this model's query results.
     *
     * @var array
     */
    protected $appends = [
        'base_amount',
    ];

    /**
     * The attributes that should automatically be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'pickup_at',
        'started_at',
        'stopped_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'creating' => BookingCreating::class,
        'deleted' => BookingDeleted::class,
        'updated' => BookingUpdated::class,
    ];

    /**
     * The attributes that are mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'full_name',
        'origin_full_address',
        'origin_address1',
        'origin_address2',
        'origin_city',
        'origin_state',
        'origin_zip',
        'origin_url',
        'destination_full_address',
        'destination_address1',
        'destination_address2',
        'destination_city',
        'destination_state',
        'destination_zip',
        'destination_url',
        'passengers',
        'airport_pickup',
        'airline',
        'flight_number',
        'departing_city',
        'notes',
        'pickup_at',
        'started_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * Generate a (hopefully) unique 16 character identifier string.
     *
     * @return string
     */
    public function generateUID()
    {
        $uid = '';
        $chars = str_split('ABCDEFGHIJKLMNOPQRSTUVWXYZ');

        while (strlen($uid) < 8) $uid .= $chars[floor(rand(0, count($chars) - 1))];

        return $uid;
    }

    /**
     * Return whether or not this booking has been abandoned.
     *
     * @return boolean
     */
    public function getAbandonedAttribute()
    {
        return !empty($this->id) && empty($this->customer_id);
    }

    /**
     * Return the starting base price for most rides ($155.00).
     *
     * @return integer
     */
    public function getBaseAmountAttribute()
    {
        return 14500;
    }

    /**
     * Return the Stripe charge for this booking.
     *
     * @return \Stripe\Charge|boolean
     */
    public function getChargeAttribute()
    {
        if (empty($this->charge_id)) return false;

        Stripe::setApiKey(config('services.stripe.secret'));

        return Charge::retrieve($this->charge_id);
    }

    /**
     * Return whether or not this booking has been paid for.
     *
     * @return boolean
     */
    public function getPaidAttribute()
    {
        return !empty($this->charge_id);
    }

    /**
     * Return the rate that this booking charges in pennies per hour.
     *
     * @return integer
     */
    public function getRateAttribute()
    {
        return 5000;
    }

    /**
     * Return whether or not this ride has been started.
     *
     * @return boolean
     */
    public function getStartedAttribute()
    {
        return !empty($this->started_at) && $this->started_at <= now() && !$this->paid;
    }

    /**
     * Return whether or not this ride is stopped and awaiting payment.
     *
     * @return boolean
     */
    public function getStoppedAttribute()
    {
        return $this->started && !empty($this->stopped_at) && !$this->paid;
    }
}

app/Http/Controllers/Admin/BookingController.php
<?php

namespace App\Http\Controllers\Admin;

use Mail;
use App\Http\Controllers\Controller;
use App\Libraries\GoogleMapPlace;
use App\Mail\BookingUpdated;
use App\Models\Booking;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Booking::withTrashed()->orderBy('pickup_at', 'desc');

        if ($request->filled('search')) {
            $query->where(function ($query) {
                $value = "%{$request->input('search')}%";

                $query->where('full_name', 'like', $value);
            });
        }

        $data['bookings'] = $query->paginate(25);

        return view('admin.bookings.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->edit(new Booking);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->update($request, new Booking);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        $data['booking'] = $booking;

        return view('admin.bookings.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Booking       $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        $rules = [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|email',
            'phone' => 'required|string|min:7|max:32',
            'airport_pickup' => 'required|in:true,false',
            'airline' => 'required_if:airport_pickup,true|nullable|string|max:255',
            'flight_number' => 'required_if:airport_pickup,true|nullable|string|max:32',
            'departing_city' => 'required_if:airport_pickup,true|nullable|string|max:255',
            'number_of_passengers' => 'required|integer|min:1|max:7',
            'datetime' => 'date|after:now',
            'notes' => 'nullable|string',
        ];

        if (empty($booking->id)) {
            $rules['pickup_location'] = 'required|json';
            $rules['destination_location'] = 'required|json';
        } else {
            $rules['pickup_location'] = 'nullable';
            $rules['destination_location'] = 'nullable';
        }

        $this->validate($request, $rules);

        $pickupLocationData = (Array) json_decode($request->input('pickup_location'));
        $destinationLocationData = (Array) json_decode($request->input('destination_location'));

        if (!empty($pickupLocationData)) $origin = new GoogleMapPlace($pickupLocationData);
        if (!empty($destinationLocationData)) $destination = new GoogleMapPlace($destinationLocationData);

        $booking->first_name = $request->input('first_name');
        $booking->last_name = $request->input('last_name');
        $booking->full_name = $request->input('first_name') . ' ' . $request->input('last_name');
        $booking->email = $request->input('email');
        $booking->phone = $request->input('phone');
        if (!empty($origin)) {
            $booking->origin_full_address = $origin->formatted_address;
            $booking->origin_address1 = $origin->street_number['long_name'] . ' ' . $origin->route['long_name'];
            $booking->origin_city = $origin->locality['long_name'];
            $booking->origin_state = $origin->administrative_area_level_1['long_name'];
            $booking->origin_zip = $origin->postal_code['long_name'];
            $booking->origin_url = $origin->url;
        }
        if (!empty($destination)) {
            $booking->destination_full_address = $destination->formatted_address;
            $booking->destination_address1 = $destination->street_number['long_name'] . ' ' . $destination->route['long_name'];
            $booking->destination_city = $destination->locality['long_name'];
            $booking->destination_state = $destination->administrative_area_level_1['long_name'];
            $booking->destination_zip = $destination->postal_code['long_name'];
            $booking->destination_url = $destination->url;
        }
        $booking->passengers = $request->input('number_of_passengers');
        $booking->pickup_at = (new Carbon($request->input('datetime')))->format('Y-m-d H:i:s');
        $booking->notes = $request->input('notes');
        $booking->airport_pickup = $request->input('airport_pickup') === 'true';
        $booking->airline = $request->input('airline') ?? null;
        $booking->flight_number = $request->input('flight_number') ?? null;
        $booking->departing_city = $request->input('departing_city') ?? null;
        $booking->save();

        return redirect(route('admin.bookings.edit', $booking))->with('success', 'Booking successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        $booking->delete();

        return redirect()->back()->with('success', 'Booking successfully cancelled. An email notification has been sent out to the individual that created the booking.');
    }

    /**
     * Un-delete the resource in storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $booking = Booking::withTrashed()->where('id', $id)->firstOrFail();

        $booking->restore();

        return redirect()->back()->with('success', 'Booking successfully restored. An email notification has been sent out to the individual that created the booking.');
    }

    /**
     * Start the clock for tracking the given booking's ride.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function start(Booking $booking)
    {
        $booking->started_at = now();
        $booking->save();

        return redirect(route('bookings.show', [ 'uid' => $booking->uid ]))->with('success', 'The ride has begun.');
    }

    /**
     * Re-sends the admin notification email w/ the booking details.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function resendNotificationEmail(Booking $booking)
    {
        $recipients = User::select(['users.name', 'users.email'])->get()->toArray();

        Mail::to($recipients)->queue(new BookingUpdated($booking));

        return redirect()->back()->with('success', 'Email successfully queued for sending.');
    }
}

resources/views/admin/bookings/edit.blade.php
@extends('layouts.admin')

@section('head')
    <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places"></script>
@endsection

@section('content')
    <admin-booking-form inline-template v-cloak>
        <form action="{{ $booking->id ? route('admin.bookings.update', $booking) : route('admin.bookings.store') }}" method="POST">
            @csrf @method($booking->id ? 'PATCH' : 'POST')

            <header class="d-flex flex-wrap justify-content-between">
                <h1>{{ $booking->id ? 'Edit' : 'Create' }} Booking</h1>

                <div class="buttons">
                    <a href="{{ route('admin.bookings.emails.notification.resend', $booking) }}">
                        <button class="btn btn-outline-primary" type="button">Re-send Notification Email</button>
                    </a>

                    <button class="btn btn-primary ml-3" type="submit">Save Booking</button>
                </div>
            </header>

            <hr class="border-white">

            @include('partials.alerts')

            @if ($booking->charge_id)
                <div class="form-group">
                    <label for="charge_id">Charge ID</label>

                    <input id="charge_id" type="text" value="{{ $booking->charge_id }}" class="form-control bg-dark text-white" disabled>
                </div>
            @endif

            @if ($booking->customer_id)
                <div class="form-group">
                    <label for="customer_id">Customer ID</label>

                    <input id="customer_id" type="text" value="{{ $booking->customer_id }}" class="form-control bg-dark text-white" disabled>
                </div>
            @endif

            <div class="form-group">
                <label for="reference_id">Reference ID</label>

                <input id="reference_id" type="text" readonly value="{{ $booking->uid }}" class="form-control bg-dark text-white">
            </div>

            <div class="form-group required">
                <label for="first_name">First Name</label>

                <input id="first_name" name="first_name" type="text" value="{{ old('first_name') ?? $booking->first_name }}" class="form-control bg-dark text-white">
            </div>

            <div class="form-group required">
                <label for="last_name">Last Name</label>

                <input id="last_name" name="last_name" type="text" value="{{ old('last_name') ?? $booking->last_name }}" class="form-control bg-dark text-white">
            </div>

            <div class="form-group required">
                <label for="email">Email</label>

                <input id="email" name="email" type="email" value="{{ old('email') ?? $booking->email }}" class="form-control bg-dark text-white">
            </div>

            <div class="form-group required">
                <label for="phone">Phone</label>

                <input id="phone" name="phone" type="text" value="{{ old('phone') ?? $booking->phone }}" class="form-control bg-dark text-white">
            </div>

            <div class="form-group required">
                <label for="pickup_location">Pickup Location</label>

                <address-search id="pickup_location" value="{{ old('pickup_location') ?? $booking->origin_full_address }}" class="form-control bg-dark text-white" v-model="origin"></address-search>

                <input type="hidden" name="pickup_location" type="text">
            </div>

            <div class="form-group">
                <label for="pickup_url">Pickup URL</label>

                <p>
                    <a target="_blank" href="{{ $booking->origin_url }}">
                        {{ $booking->origin_url }}
                    </a>
                </p>
            </div>

            <div class="form-group required">
                <label for="destination_location">Destination Location</label>

                <address-search id="destination_location" value="{{ old('destination_location') ?? $booking->destination_full_address }}" class="form-control bg-dark text-white" v-model="destination"></address-search>

                <input type="hidden" name="destination_location" type="text">
            </div>

            <div class="form-group">
                <label for="destination_url">Destination URL</label>

                <p>
                    <a target="_blank" href="{{ $booking->destination_url }}">
                        {{ $booking->destination_url }}
                    </a>
                </p>
            </div>

            <div class="form-group">
                <label for="number_of_passengers">Number of Passengers</label>

                <select id="number_of_passengers" name="number_of_passengers" class="form-control bg-dark text-white border-dark">
                    <option value="1" {{ $booking->passengers === '1' ? 'selected' : '' }}>1 passenger</option>

                    <option value="2" {{ $booking->passengers === '2' ? 'selected' : '' }}>2 passengers</option>

                    <option value="3" {{ $booking->passengers === '3' ? 'selected' : '' }}>3 passengers</option>

                    <option value="4" {{ $booking->passengers === '4' ? 'selected' : '' }}>4 passengers</option>

                    <option value="5" {{ $booking->passengers === '5' ? 'selected' : '' }}>5 passengers</option>

                    <option value="6" {{ $booking->passengers === '6' ? 'selected' : '' }}>6 passengers</option>

                    <option value="7" {{ $booking->passengers === '7' ? 'selected' : '' }}>7 passengers (with minimal luggage)</option>
                </select>
            </div>

            <div class="form-group required">
                <label for="airport_pickup">Airport Pickup</label>

                @php $oldAirport = old('airport_pickup') ? old('airport_pickup') == 'true' : $booking->airport_pickup; @endphp

                <select id="airport_pickup" name="airport_pickup" class="form-control bg-dark text-white">
                    <option value="false" {{ $oldAirport ? 'selected' : '' }}>No</option>

                    <option value="true" {{ $oldAirport ? 'selected' : '' }}>Yes</option>
                </select>
            </div>

            <dependent on="airport_pickup" value="true" class="form-group required" v-cloak>
                <label for="airline">Airline</label>

                <input id="airline" name="airline" type="text" value="{{ old('airline') ?? $booking->airline }}" class="form-control bg-dark text-white">
            </dependent>

            <dependent on="airport_pickup" value="true" class="form-group required" v-cloak>
                <label for="flight_number">Flight Number</label>

                <input id="flight_number" name="flight_number" type="text" value="{{ old('flight_number') ?? $booking->flight_number }}" class="form-control bg-dark text-white">
            </dependent>

            <dependent on="airport_pickup" value="true" class="form-group required" v-cloak>
                <label for="departing_city">Departing City</label>

                <input id="departing_city" name="departing_city" type="text" value="{{ old('departing_city') ?? $booking->departing_city }}" class="form-control bg-dark text-white">
            </dependent>

            <div class="form-group">
                <label for="notes">Notes</label>

                <textarea id="notes" name="notes" rows="5" class="form-control bg-dark text-white">{{ old('notes') ?? $booking->notes }}</textarea>
            </div>

            <button class="btn btn-primary" type="submit">Save Booking</button>
        </form>
    </admin-booking-form>
@endsection

resources/views/admin/bookings/index.blade.php
@extends('layouts.admin')

@section('content')
    <header class="d-flex flex-wrap justify-content-between">
        <h1>Bookings</h1>
    </header>

    @include('partials.alerts')

    <table class="table table-striped bg-dark">
        <thead>
            <tr>
                <th>
                    Status
                </th>

                <th>
                    Customer
                </th>

                <th>
                    Pickup At
                </th>

                <th class="fit"></th>

                <th class="fit"></th>

                <th class="fit"></th>
            </tr>
        </thead>

        <tbody>
            @if ($bookings->count())
                @foreach ($bookings as $booking)
                    <tr>
                        <td>
                            @if ($booking->paid)
                                <span class="badge badge-success">Paid</span>
                            @elseif ($booking->trashed())
                                <span class="badge badge-danger">Cancelled</span>
                            @elseif ($booking->stopped)
                                <span class="badge badge-secondary">Stopped</span>
                            @elseif ($booking->started)
                                <span class="badge badge-warning">In Progress</span>
                            @elseif ($booking->abandoned)
                                <span class="badge badge-secondary">Abandoned</span>
                            @else
                                <span class="badge badge-primary">Booked</span>
                            @endif
                        </td>

                        <td>
                            {{ $booking->first_name }} {{ $booking->last_name }} &lt;{{ $booking->email }}&gt;
                        </td>

                        <td>
                            @if ($booking->pickup_at >= today() && $booking->pickup_at < tomorrow())
                                {{ $booking->pickup_at->format('g:ia') }} Today
                            @elseif ($booking->pickup_at >= tomorrow() && $booking->pickup_at < dayAfterTomorrow())
                                {{ $booking->pickup_at->format('g:ia') }} Tomorrow
                            @else
                                {{ $booking->pickup_at->format('g:ia T \o\n F jS, Y') }}
                            @endif
                        </td>

                        <td class="fit">
                            @if (!$booking->abandoned && !$booking->trashed())
                                @if (!$booking->started && !$booking->paid)
                                    <form action="{{ route('admin.bookings.start', $booking) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to start the ride?')) return false;">
                                        @csrf @method('PATCH')

                                        <button class="btn btn-outline-success" type="submit" title="Start Ride">
                                            Start Ride
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('bookings.show', [ 'uid' => $booking->uid ]) }}">
                                        <button class="btn btn-outline-success" type="button">
                                            View {{ $booking->paid ? 'Receipt' : 'Ride' }}
                                        </button>
                                    </a>
                                @endif
                            @endif
                        </td>

                        <td class="fit">
                            @if (!$booking->trashed())
                                <a href="{{ route('admin.bookings.edit', $booking) }}" title="Edit Booking">
                                    <button class="btn btn-primary" type="button">
                                        Edit
                                    </button>
                                </a>
                            @else
                                <a target="_blank" href="{{ route('bookings.show', [ 'uid' => $booking->uid ]) }}" title="View Booking">
                                    <button class="btn btn-outline-light" type="button">
                                        View
                                    </button>
                                </a>
                            @endif
                        </td>

                        <td class="fit">
                            @if (!$booking->abandoned)
                                @if (!$booking->trashed())
                                    <form action="{{ route('admin.bookings.destroy', $booking) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to cancel this booking? The individual that created the booking will receive a cancellation notice email.')) return false;">
                                        @csrf @method('DELETE')

                                        <button class="btn btn-outline-danger" type="submit" title="Cancel Booking">
                                            Cancel
                                        </button>
                                    </form>
                                @else
                                    <form action="{{ route('admin.bookings.restore', $booking) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to restore this booking? The individual that created the booking will receive a restoration notice email.')) return false;">
                                        @csrf @method('PATCH')

                                        <button class="btn btn-outline-success" type="submit" title="Restore Booking">
                                            Restore
                                        </button>
                                    </form>
                                @endif
                            @endif
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="4">
                        There are currently no bookings matching your criteria.
                    </td>
                </tr>
            @endif
        </tbody>
    </table>
@endsection