routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::post('bookings', 'BookingController@store')->name('bookings.store');
Route::get('bookings/{uid}', 'BookingController@show')->name('bookings.show');
Route::get('bookings/{uid}/edit', 'BookingController@edit')->name('bookings.edit');
Route::delete('bookings/{uid}', 'BookingController@destroy')->name('bookings.destroy');
Route::post('bookings/{uid}/update', 'BookingController@update')->name('bookings.update');
Route::post('bookings/{uid}/stop', 'BookingController@stop')->name('bookings.stop');
Route::post('bookings/{uid}/resume', 'BookingController@resume')->name('bookings.resume');
Route::get('bookings/{uid}/pay', 'BookingController@getPay')->name('bookings.pay');
Route::post('bookings/{uid}/pay', 'BookingController@postPay')->name('bookings.pay.post');

Route::get('contact', 'ContactController@form')->name('contact');
Route::post('contact', 'ContactController@send')->name('contact.post');
Route::get('contact/thanks', 'ContactController@thanks')->name('contact.thanks');

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::redirect('/', '/admin/bookings');

    Route::patch('bookings/{booking}/start', 'BookingController@start')->name('bookings.start');
    Route::patch('bookings/{booking}/restore', 'BookingController@restore')->name('bookings.restore');
    Route::get('bookings/{booking}/emails/notification/resend', 'BookingController@resendNotificationEmail')->name('bookings.emails.notification.resend');
    Route::resource('bookings', 'BookingController')->except(['create', 'show']);

    Route::get('black-outs', 'BlackOutController@index')->name('black-outs.index');
    Route::get('black-outs/create', 'BlackOutController@create')->name('black-outs.create');
    Route::post('black-outs', 'BlackOutController@store')->name('black-outs.store');
    Route::get('black-outs/{blackOut}/edit', 'BlackOutController@edit')->name('black-outs.edit');
    Route::patch('black-outs/{blackOut}', 'BlackOutController@update')->name('black-outs.update');
    Route::delete('black-outs/{blackOut}', 'BlackOutController@destroy')->name('black-outs.destroy');

    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/create', 'UserController@create')->name('users.create');
    Route::post('users', 'UserController@store')->name('users.store');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::patch('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
});

app/Models/BlackOut.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BlackOut extends Model
{
    /**
     * The attributes that should be cast to dates.
     *
     * @var array
     */
    protected $dates = [
        'starts_on',
        'ends_on',
    ];

    /**
     * The attributes that are mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'starts_on',
        'ends_on',
    ];

    /**
     * Return future black-out dates in a format that the Flatpickr component can consume.
     *
     * @return array
     */
    public static function forView()
    {
        return self::query()
            ->where('starts_on', '>=', now())
            ->get()
            ->map(function ($item, $key) {
                return [
                    'from' => $item->starts_on->format('Y-m-d'),
                    'to' => $item->ends_on->format('Y-m-d'),
                ];
            })
            ->toJson();
    }
}

app/Http/Controllers/Admin/BlackOutController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlackOut;
use Illuminate\Http\Request;

class BlackOutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illumiante\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = BlackOut::query();

        if ($request->filled('search')) {
            $query->where('name', 'like', "%{$request->input('search')}%");
        }

        $data['blackOuts'] = $query->paginate(25);

        return view('admin.black-outs.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->edit(new BlackOut);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->update($request, new BlackOut);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BlackOut  $blackOut
     * @return \Illuminate\Http\Response
     */
    public function edit(BlackOut $blackOut)
    {
        return view('admin.black-outs.edit', [ 'blackOut' => $blackOut, ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BlackOut      $blackOut
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BlackOut $blackOut)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'starts_on' => 'required|date_format:Y-m-d|before:ends_on',
            'ends_on' => 'required|date_format:Y-m-d|after:starts_on',
        ]);

        $blackOut->fill($request->only('name', 'starts_on', 'ends_on'));
        $blackOut->save();

        return redirect(route('admin.black-outs.index'))->with('success', 'Black-out dates successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BlackOut  $blackOut
     * @return \Illuminate\Http\Response
     */
    public function destroy(BlackOut $blackOut)
    {
        $blackOut->delete();

        return redirect(route('admin.black-outs.index'))->with('success', 'Black-out dates successfully deleted.');
    }
}

resources/views/admin/black-outs/edit.blade.php
@extends('layouts.admin')

@section('content')
    <form action="{{ $blackOut->id ? route('admin.black-outs.update', $blackOut) : route('admin.black-outs.store') }}" method="POST">
        @csrf @method($blackOut->id ? 'PATCH' : 'POST')

        <header class="d-flex flex-wrap justify-content-between">
            <h1>
                {{ $blackOut->id ? 'Edit' : 'Create' }} Black-out Dates
            </h1>

            <button class="btn btn-primary" type="submit">
                Save Black-out Dates
            </button>
        </header>

        <hr class="border-white">

        @include('partials.alerts')

        <div class="form-group required">
            <label for="name">Name</label>

            <input id="name" name="name" type="text" value="{{ old('name') ?? $blackOut->name }}" class="form-control bg-dark text-white">

            <small>
                <em class="text-muted">
                    This field is just for reference and doesn't appear on the booking form.
                </em>
            </small>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group required">
                    <label for="starts_on">Starts On</label>

                    <flatpickr
                        id="starts_on"
                        name="starts_on"
                        value="{{ old('starts_on') ?? (!empty($blackOut->starts_on) ? $blackOut->starts_on->format('Y-m-d') : '') }}"
                        class="form-control bg-dark text-white"
                    ></flatpickr>

                    <small>
                        <em class="text-muted">
                            This is the start of the date range that you do not want to be available on the booking form.
                        </em>
                    </small>
                </div>
            </div>

            <div class="col">
                <div class="form-group required">
                    <label for="ends_on">Ends On</label>

                    <flatpickr
                        id="ends_on"
                        name="ends_on"
                        value="{{ old('ends_on') ?? (!empty($blackOut->ends_on) ? $blackOut->ends_on->format('Y-m-d') : '') }}"
                        class="form-control bg-dark text-white"
                    ></flatpickr>

                    <small>
                        <em class="text-muted">
                            This is the end of the date range that you do not want to be available on the booking form.
                        </em>
                    </small>
                </div>
            </div>
        </div>

        <button class="btn btn-primary" type="submit">
            Save Black-out Dates
        </button>
    </form>
@endsection

resources/views/admin/black-outs/index.blade.php
@extends('layouts.admin')

@section('content')
    <header class="d-flex flex-wrap justify-content-between">
        <h1>
            Black-out Dates
        </h1>

        <a href="{{ route('admin.black-outs.create') }}">
            <button class="btn btn-primary" type="button">
                Add New Black-out Dates
            </button>
        </a>
    </header>

    @include('partials.alerts')

    <table class="table table-striped bg-dark">
        <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Starts On
                </th>

                <th>
                    Ends On
                </th>

                <th>
                    <!-- Edit -->
                </th>

                <th>
                    <!-- Delete -->
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach ($blackOuts as $blackOut)
                <tr>
                    <td>
                        {{ $blackOut->name }}
                    </td>

                    <td>
                        {{ $blackOut->starts_on->format('F jS, Y') }}
                    </td>

                    <td>
                        {{ $blackOut->ends_on->format('F jS, Y') }}
                    </td>

                    <td>
                        <a href="{{ route('admin.black-outs.edit', $blackOut) }}" title="Edit Black-out Dates">
                            <button class="btn btn-primary" type="button">
                                Edit
                            </button>
                        </a>
                    </td>

                    <td>
                        <form action="{{ route('admin.black-outs.destroy', $blackOut) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to delete these black-out dates?')) return false;">
                            @csrf @method('DELETE')

                            <button class="btn btn-outline-danger" type="submit" title="Delete Black-out Dates">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>

                {{ $blackOuts->appends(request()->all())->links() }}
            @endforeach
        </tbody>
    </table>
@endsection