routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::post('bookings', 'BookingController@store')->name('bookings.store');
Route::get('bookings/{uid}', 'BookingController@show')->name('bookings.show');
Route::get('bookings/{uid}/edit', 'BookingController@edit')->name('bookings.edit');
Route::delete('bookings/{uid}', 'BookingController@destroy')->name('bookings.destroy');
Route::post('bookings/{uid}/update', 'BookingController@update')->name('bookings.update');
Route::post('bookings/{uid}/stop', 'BookingController@stop')->name('bookings.stop');
Route::post('bookings/{uid}/resume', 'BookingController@resume')->name('bookings.resume');
Route::get('bookings/{uid}/pay', 'BookingController@getPay')->name('bookings.pay');
Route::post('bookings/{uid}/pay', 'BookingController@postPay')->name('bookings.pay.post');

Route::get('contact', 'ContactController@form')->name('contact');
Route::post('contact', 'ContactController@send')->name('contact.post');
Route::get('contact/thanks', 'ContactController@thanks')->name('contact.thanks');

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::redirect('/', '/admin/bookings');

    Route::patch('bookings/{booking}/start', 'BookingController@start')->name('bookings.start');
    Route::patch('bookings/{booking}/restore', 'BookingController@restore')->name('bookings.restore');
    Route::get('bookings/{booking}/emails/notification/resend', 'BookingController@resendNotificationEmail')->name('bookings.emails.notification.resend');
    Route::resource('bookings', 'BookingController')->except(['create', 'show']);

    Route::get('black-outs', 'BlackOutController@index')->name('black-outs.index');
    Route::get('black-outs/create', 'BlackOutController@create')->name('black-outs.create');
    Route::post('black-outs', 'BlackOutController@store')->name('black-outs.store');
    Route::get('black-outs/{blackOut}/edit', 'BlackOutController@edit')->name('black-outs.edit');
    Route::patch('black-outs/{blackOut}', 'BlackOutController@update')->name('black-outs.update');
    Route::delete('black-outs/{blackOut}', 'BlackOutController@destroy')->name('black-outs.destroy');

    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/create', 'UserController@create')->name('users.create');
    Route::post('users', 'UserController@store')->name('users.store');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::patch('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'receives_contact_form',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Set the middleware.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = User::orderBy('name');

        if ($request->filled('search')) {
            $query->where(function ($query) use ($request) {
                $value = "%{$request->input('search')}%";

                $query->where('name', 'like', $value);
                $query->orWhere('email', 'like', $value);
            });
        }

        $data['users'] = $query->paginate(25);

        return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->edit(new User());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->update($request, new User());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $data['user'] = $user;

        return view('admin.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User          $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => "required|email|unique:users,email,{$user->id}",
            'password' => 'nullable|min:6|confirmed',
            'receives_contact_form' => 'nullable|in:yes,no',
        ]);

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        if ($request->filled('password')) $user->password = bcrypt($request->input('password'));
        $user->receives_contact_form = $request->input('receives_contact_form') === 'yes';
        $user->save();

        return redirect(route('admin.users.edit', $user))->with('success', 'User successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->back()->with('success', 'User successfully deleted.');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
    <form action="{{ $user->id ? route('admin.users.update', $user) : route('admin.users.store') }}" method="POST">
        @csrf @method($user->id ? 'PATCH' : 'POST')

        <header class="d-flex flex-wrap justify-content-between">
            <h1>{{ $user->id ? 'Edit' : 'Create' }} User</h1>

            <button class="btn btn-primary" type="submit">Save User</button>
        </header>

        <hr class="border-white">

        @include('partials.alerts')

        <div class="form-group required">
            <label for="name">Name</label>

            <input id="name" name="name" type="text" value="{{ old('name') ?? $user->name }}" class="form-control bg-dark text-white">
        </div>

        <div class="form-group required">
            <label for="email">Email</label>

            <input id="email" name="email" type="email" value="{{ old('email') ?? $user->email }}" class="form-control bg-dark text-white">
        </div>

        <div class="form-group">
            <label for="password">Password</label>

            <input id="password" name="password" type="password" class="form-control bg-dark text-white">
        </div>

        <div class="form-group">
            <label for="password_confirmation">Confirm Password</label>

            <input id="password_confirmation" name="password_confirmation" type="password" class="form-control bg-dark text-white">
        </div>

        <div class="form-group">
            <label for="receives_contact_form">Receives Contact Form</label>

            <select id="receives_contact_form" name="receives_contact_form" class="form-control bg-dark text-white">
                <option value="no" {{ $user->receives_contact_form ? '' : 'selected' }}>No</option>

                <option value="yes" {{ $user->receives_contact_form ? 'selected' : '' }}>Yes</option>
            </select>
        </div>

        <button class="btn btn-primary" type="submit">Save User</button>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    <header class="d-flex flex-wrap justify-content-between">
        <h1>Users</h1>

        <a href="{{ route('admin.users.create') }}">
            <button class="btn btn-primary" type="button">Create User</button>
        </a>
    </header>

    @include('partials.alerts')

    <table class="table table-striped bg-dark">
        <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Email
                </th>

                <th></th>

                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>
                        {{ $user->name }}
                    </td>

                    <td>
                        {{ $user->email }}
                    </td>

                    <td>
                        <a href="{{ route('admin.users.edit', $user) }}" title="Edit User">
                            <button class="btn btn-primary" type="button">
                                Edit
                            </button>
                        </a>
                    </td>

                    <td>
                        <form action="{{ route('admin.users.destroy', $user) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to delete this user?')) return false;">
                            @csrf @method('DELETE')

                            <button class="btn btn-outline-danger" type="submit" title="Delete User">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection